name: HousingPricePredictor
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - jupyter
  - pytest
  - pip
  - pip:
    - python-dotenv
    - tqdm
